name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container image
        run: docker build -t devopster-cli-ci .
      - name: Run build in container
        run: docker run --rm devopster-cli-ci cargo build --locked
      - name: Run tests in container
        run: docker run --rm devopster-cli-ci cargo test --locked
      - name: Run lint in container
        run: docker run --rm devopster-cli-ci cargo clippy --all-targets --all-features -- -D warnings
